ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    
    # Fast LIO 里程计输入
    odom0: /Odometry
    odom0_config: [true, true, true, false, false, false, true, true, true, false, false, true, false, false, false]
    odom0_differential: false
    odom0_relative: false
    
    # IMU 输入（如果有）
    imu0: /livox/imu
    imu0_config: [false, false, false, true, true, true, false, false, false, true, true, true, true, true, true]
    imu0_differential: true
    
    use_control: false
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom